version: "3.8"

x-environment: &environment
  DEBUG: ${DEBUG}

  DB_HOST: wallet-screener-postgres
  DB_NAME: ${DB_NAME}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}

services:
  wallet-screener-scanner:
    container_name: wallet-screener-scanner
    build: ./src
    command: python -m src.domain.scanner
    volumes:
      - ./src:/usr/app/src
    environment:
      <<: *environment
    depends_on:
      - wallet-screener-postgres

  wallet-screener-postgres:
    container_name: wallet-screener-postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - v_wallet-screener_postgres:/var/lib/postgresql/data

volumes:
  v_wallet-screener_postgres:
  v_wallet-screener_grafana:
