"""init

Revision ID: 146d58395ebb
Revises: 825d6ad33eb1
Create Date: 2024-09-10 10:55:19.865446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146d58395ebb'
down_revision = '825d6ad33eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('txn_hash', sa.String(length=256), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pools_created_at'), 'pools', ['created_at'], unique=False)
    op.add_column('swaps', sa.Column('transaction_id', sa.BigInteger(), nullable=True))
    op.add_column('swaps', sa.Column('from_token_id', sa.Integer(), nullable=True))
    op.add_column('swaps', sa.Column('from_token_amount', sa.Numeric(precision=60, scale=0), nullable=True))
    op.add_column('swaps', sa.Column('to_token_id', sa.Integer(), nullable=True))
    op.add_column('swaps', sa.Column('to_token_amount', sa.Numeric(precision=60, scale=0), nullable=True))
    op.create_index(op.f('ix_swaps_from_token_id'), 'swaps', ['from_token_id'], unique=False)
    op.create_index(op.f('ix_swaps_to_token_id'), 'swaps', ['to_token_id'], unique=False)
    op.create_index(op.f('ix_swaps_transaction_id'), 'swaps', ['transaction_id'], unique=False)
    op.drop_constraint('swaps_trader_id_fkey', 'swaps', type_='foreignkey')
    op.drop_constraint('swaps_pool_id_fkey', 'swaps', type_='foreignkey')
    op.create_foreign_key(None, 'swaps', 'tokens', ['to_token_id'], ['id'])
    op.create_foreign_key(None, 'swaps', 'tokens', ['from_token_id'], ['id'])
    op.create_foreign_key(None, 'swaps', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('swaps', 'pool_token1_delta')
    op.drop_column('swaps', 'block_number')
    op.drop_column('swaps', 'pool_token0_delta')
    op.drop_column('swaps', 'txn_hash')
    op.drop_column('swaps', 'pool_id')
    op.drop_column('swaps', 'trader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('trader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swaps', sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swaps', sa.Column('txn_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('swaps', sa.Column('pool_token0_delta', sa.NUMERIC(precision=64, scale=0), autoincrement=False, nullable=True))
    op.add_column('swaps', sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swaps', sa.Column('pool_token1_delta', sa.NUMERIC(precision=64, scale=0), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.create_foreign_key('swaps_pool_id_fkey', 'swaps', 'pools', ['pool_id'], ['id'])
    op.create_foreign_key('swaps_trader_id_fkey', 'swaps', 'traders', ['trader_id'], ['id'])
    op.drop_index(op.f('ix_swaps_transaction_id'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_to_token_id'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_from_token_id'), table_name='swaps')
    op.drop_column('swaps', 'to_token_amount')
    op.drop_column('swaps', 'to_token_id')
    op.drop_column('swaps', 'from_token_amount')
    op.drop_column('swaps', 'from_token_id')
    op.drop_column('swaps', 'transaction_id')
    op.drop_index(op.f('ix_pools_created_at'), table_name='pools')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
