"""init

Revision ID: 825d6ad33eb1
Revises: 
Create Date: 2024-09-10 09:44:27.801652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825d6ad33eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errors_created_at'), 'errors', ['created_at'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traders_address'), 'traders', ['address'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('token0_id', sa.Integer(), nullable=True),
    sa.Column('token1_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['token0_id'], ['tokens.id'], ),
    sa.ForeignKeyConstraint(['token1_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_contract'), 'pools', ['contract'], unique=False)
    op.create_table('swaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('txn_hash', sa.String(length=256), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('pool_token0_delta', sa.NUMERIC(precision=64, scale=0), nullable=True),
    sa.Column('pool_token1_delta', sa.NUMERIC(precision=64, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swaps_created_at'), 'swaps', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swaps_created_at'), table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_pools_contract'), table_name='pools')
    op.drop_table('pools')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_traders_address'), table_name='traders')
    op.drop_table('traders')
    op.drop_table('networks')
    op.drop_index(op.f('ix_errors_created_at'), table_name='errors')
    op.drop_table('errors')
    # ### end Alembic commands ###
